### ISSUE TITLE
Your tech blog

### ISSUE THREAD

**Issue by rpbaptist** [xiranou/xiranou.github.io#1]
Hi there! When I saw your feedback on my post I figured you must have finished yours as well and I was happy to have a look.

It makes a lot of sense to pick Wikipedia! I use it so often that I tend to overlook it as as website.

Your blog site is very complete, with a menu to the left. I know it's a work in progress, but it's nice to see a more complete website in place. I like the dotted seperator at the top in combination with the color background color. It comes off as a more classical approach.

One thing I notice is that you use different fonts for the menu, the title and the paragraph. This can work well, but the styles seem very far apart from eachother. With different fonts your site could immediately look more unified.

Thanks for leaving feedback and I like that your links don't take me away from the page either. :)

**Comment by xiranou** [comment]
Thanks for the feedback! After many testing, I think I have a more consistent font style now.
