### ISSUE TITLE
Tech blog feedback

### ISSUE THREAD

**Issue by lymanwong** [xiranou/xiranou.github.io#2]
Hello there,

I like the use of pictures and examples, but you could elaborate a bit more about each example in common terms.  I think of it as explaining it to my grandmother.  :)  You could also describe the image and what they mean.  The contact me link doesn't seem to go anywhere as well.  I really like the look of your icons at the bottom and the use of the dotted lines to separate the header and footer.  Perhaps you may want to consider adding a container or wrapper for your paragraphs.

**Comment by xiranou** [comment]
Thanks for the feedback! I have fixed the link now, it should work properly. I've also taken you advice and added more to explain my pictures and examples.
